### PR TITLE
remove pandas upperbound

### PR DESCRIPTION
**Pull request by marctorsoc**

### CODE REVIEW

**Comment by marctorsoc** [comment]
This seems to work, any reason not to do it? @ynqa

**Comment by ynqa** [comment]
@marctorsoc  The following warnings were emitted on testing with pandas v1.3.5, and so I planed to include 1.3.x after they are removed.

```
$ pytest -vvv .
========================================== test session starts ===========================================
platform linux -- Python 3.7.9, pytest-7.1.2, pluggy-1.0.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /app
collected 9 items

tests/pandavro_test.py::test_schema_infer PASSED                                                   [ 11%]
tests/pandavro_test.py::test_schema_infer_times_as_millis PASSED                                   [ 22%]
tests/pandavro_test.py::test_schema_infer_complex_types PASSED                                     [ 33%]
tests/pandavro_test.py::test_fields_infer PASSED                                                   [ 44%]
tests/pandavro_test.py::test_buffer_e2e PASSED                                                     [ 55%]
tests/pandavro_test.py::test_file_path_e2e PASSED                                                  [ 66%]
tests/pandavro_test.py::test_delegation PASSED                                                     [ 77%]
tests/pandavro_test.py::test_append PASSED                                                         [ 88%]
tests/pandavro_test.py::test_dataframe_kwargs PASSED                                               [100%]

============================================ warnings summary ============================================
tests/pandavro_test.py::test_buffer_e2e
  /app/tests/pandavro_test.py:110: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
    expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))

tests/pandavro_test.py::test_file_path_e2e
  /app/tests/pandavro_test.py:118: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
    expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))

tests/pandavro_test.py::test_delegation
  /app/tests/pandavro_test.py:126: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
    expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))

tests/pandavro_test.py::test_append
  /app/tests/pandavro_test.py:135: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
    expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))

tests/pandavro_test.py::test_dataframe_kwargs
  /app/tests/pandavro_test.py:150: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
    expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))

tests/pandavro_test.py::test_dataframe_kwargs
  /app/tests/pandavro_test.py:156: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
    expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================== 9 passed, 6 warnings in 0.24s ======================================
```

**Comment by marctorsoc** [comment]
> @marctorsoc Yes it's working, but the following warnings were emitted on testing with pandas v1.3.5, and so I planned to include 1.3.x after they are removed.
> 
> ```
> $ pytest -vvv .
> ========================================== test session starts ===========================================
> platform linux -- Python 3.7.9, pytest-7.1.2, pluggy-1.0.0 -- /usr/local/bin/python
> cachedir: .pytest_cache
> rootdir: /app
> collected 9 items
> 
> tests/pandavro_test.py::test_schema_infer PASSED                                                   [ 11%]
> tests/pandavro_test.py::test_schema_infer_times_as_millis PASSED                                   [ 22%]
> tests/pandavro_test.py::test_schema_infer_complex_types PASSED                                     [ 33%]
> tests/pandavro_test.py::test_fields_infer PASSED                                                   [ 44%]
> tests/pandavro_test.py::test_buffer_e2e PASSED                                                     [ 55%]
> tests/pandavro_test.py::test_file_path_e2e PASSED                                                  [ 66%]
> tests/pandavro_test.py::test_delegation PASSED                                                     [ 77%]
> tests/pandavro_test.py::test_append PASSED                                                         [ 88%]
> tests/pandavro_test.py::test_dataframe_kwargs PASSED                                               [100%]
> 
> ============================================ warnings summary ============================================
> tests/pandavro_test.py::test_buffer_e2e
>   /app/tests/pandavro_test.py:110: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
>     expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))
> 
> tests/pandavro_test.py::test_file_path_e2e
>   /app/tests/pandavro_test.py:118: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
>     expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))
> 
> tests/pandavro_test.py::test_delegation
>   /app/tests/pandavro_test.py:126: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
>     expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))
> 
> tests/pandavro_test.py::test_append
>   /app/tests/pandavro_test.py:135: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
>     expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))
> 
> tests/pandavro_test.py::test_dataframe_kwargs
>   /app/tests/pandavro_test.py:150: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
>     expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))
> 
> tests/pandavro_test.py::test_dataframe_kwargs
>   /app/tests/pandavro_test.py:156: FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
>     expect['DateTime64'] = expect['DateTime64'].astype(np.dtype('datetime64[ns]'))
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> ===================================== 9 passed, 6 warnings in 0.24s ======================================
> ```

@ynqa solved :)

**Review by ynqa — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
