### PR TITLE
less memory usage when writing a dataframe

### PR DESCRIPTION
**Pull request by slemouzy**
Instead of converting the whole DataFrame into a list of dicts (which can double the memory usage), uses a Generator function to iterate on the rows of the DataFrame converting each row one after the other.

### CODE REVIEW

**Comment by marctorsoc** [comment]
@slemouzy  this seems like a nice addition. Could you fix the conflicts? @ynqa would you agree to add this?

**Comment by ynqa** [comment]
> would you agree to add this?

@marctorsoc Basically, yes. What about leaving the existing implementation as is?

**Comment by marctorsoc** [comment]
I don't quite understand your comment. The current implementation does
```
    records = __preprocess_dicts(df.to_dict('records'))
```
[here](https://github.com/ynqa/pandavro/blob/master/pandavro/__init__.py#L339), which means doubling the memory as the OP is trying to fix

I did not review the specific implementation in the PR, but I'm sure if he knows you'll approve, he'll be more motivated to fix the conflicts 😃 . Worst case scenario, I'm happy to fix it

**Comment by ynqa** [comment]
@marctorsoc Thank you, I misunderstood. Let's incorporate this change.

**Comment by slemouzy** [comment]
> @slemouzy this seems like a nice addition. Could you fix the conflicts? @ynqa would you agree to add this?

Let see what I can do, I'll maybe be able to have some time on it during my weekend. Glad you've been able to look at my proposal. :slightly_smiling_face:

**Review by ynqa — APPROVED** [review]
LGTM!

**Pull request merged**
